# 运行模式(debug:调试,test:测试,release:正式)
RunMode = "debug"


[WebSocket]
# ID
ID = "ws"
# 监听地址
Address = ":8888"
# 证书路径
CertFile = ""
# 证书密钥
KeyFile = ""


[Postgres]
# 连接地址
Host = "127.0.0.1"
# 连接端口
Port = 5432
# 用户名
User = "postgres"
# 密码
Password = "123456"
# 数据库
DBName = "gin-admin"
# SSL模式
SSLMode = "disable"